# Generated by Django 4.2.16 on 2024-11-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMiaAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='imagenPlato',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
