# Generated by Django 4.2.16 on 2024-11-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMiaAPP', '0002_plato_imagenplato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='imagenPlato',
            field=models.URLField(blank=True, max_length=60, null=True),
        ),
    ]
