# Generated by Django 5.1.2 on 2024-11-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMiaAPP', '0003_alter_plato_imagenplato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='menu',
        ),
        migrations.AddField(
            model_name='plato',
            name='menu',
            field=models.ManyToManyField(related_name='platos', to='MammaMiaAPP.menu'),
        ),
    ]
