# Generated by Django 5.1.2 on 2024-11-28 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMiaAPP', '0004_remove_plato_menu_plato_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='plato',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='menu',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='plato',
            field=models.ManyToManyField(related_name='ingredientes', to='MammaMiaAPP.plato'),
        ),
        migrations.AddField(
            model_name='plato',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platos', to='MammaMiaAPP.menu'),
        ),
    ]
