# Generated by Django 5.1.3 on 2024-11-30 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMiaAPP', '0005_remove_ingrediente_plato_remove_plato_menu_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingrediente',
            options={'permissions': [('can_view_ingrediente', 'Can view ingrediente'), ('can_edit_ingrediente', 'Can edit ingrediente')]},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'permissions': [('can_view_menu', 'Can view menu'), ('can_edit_menu', 'Can edit menu')]},
        ),
        migrations.AlterModelOptions(
            name='plato',
            options={'permissions': [('can_view_plato', 'Can view plato'), ('can_edit_plato', 'Can edit plato')]},
        ),
    ]
